name: restheart-native

services:
  restheart:
    image: softinstigate/restheart:latest-native
    environment:
      RHO: >
          /core/name->"native";
          /mclient/connection-string->"mongodb://mongodb";
          /http-listener/host->"0.0.0.0";
    depends_on:
      mongodb:
        condition: service_healthy
    # you can add javascript plugins mounting the following directory
    # volumes:
    #   - ./plugins:/opt/restheart/plugins
    ports:
      - "8080:8080"

  mongodb:
    image: mongo:7.0
    command: ["--bind_ip_all", "--replSet", "rs0"]
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "'if (!rs.isMaster().ismaster) { rs.initiate(); }'"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 5s
