name: Native MacOS Image

on: workflow_dispatch # Manually trigger the workflow

jobs:
  build-and-upload:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            arch: "darwin-amd64"
          - os: macos-latest
            arch: "darwin-arm64"
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4

      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: "21"
          distribution: "graalvm-community"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache: "maven"
          native-image-job-reports: "true"

      - name: Build darwin-amd64 (Intel) native
        if: matrix.os == 'macos-latest' && matrix.arch == 'darwin-amd64'
        run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          java --version
          native-image --version
          mvn package -Pnative -DskipTests -Dnative.march="-march=x86-64"
          chmod +x core/target/restheart

      - name: Upload darwin-amd64 (Intel) native
        if: matrix.os == 'macos-latest' && matrix.arch == 'darwin-amd64'
        uses: actions/upload-artifact@v4
        with:
          name: restheart-darwin-amd64
          path: core/target/restheart
          overwrite: true

      - name: Build darwin-arm64 (Apple Silicon) native
        if: matrix.os == 'macos-latest' && matrix.arch == 'darwin-arm64'
        run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          java --version
          native-image --version
          mvn package -Pnative -DskipTests -Dnative.march="-march=armv8-a"
          chmod +x core/target/restheart

      - name: Upload darwin-arm64 (Apple Silicon) native
        if: matrix.os == 'macos-latest' && matrix.arch == 'darwin-arm64'
        uses: actions/upload-artifact@v4
        with:
          name: restheart-darwin-arm64
          path: core/target/restheart
          overwrite: true
