name: Native Image Release

on: workflow_dispatch # Manually trigger the workflow

jobs:
  build-and-upload:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: "linux-amd64"
          - os: windows-latest
            arch: "windows-amd64"
          - os: macos-latest
            arch: "macos-arm64"
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    outputs:
      ubuntu: ${{ steps.set-output.outputs.ubuntu }}
    steps:
      - uses: actions/checkout@v4

      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: "21"
          distribution: "graalvm-community"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache: "maven"
          native-image-job-reports: "true"

      - name: Build native image
        run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          java --version
          native-image --version
          mvn package -Pnative -DskipTests

      - name: Set Output for Ubuntu
        if: matrix.arch == 'linux-amd64'
        id: set-output
        run: echo "ubuntu=true" >> $GITHUB_ENV

      # Upload the binary artifact for linux-amd64 only
      - name: Upload Binary Artifact
        if: matrix.arch == 'linux-amd64'
        uses: actions/upload-artifact@v4
        with:
          name: restheart
          path: core/target/restheart

      - name: Upload Binary to Release
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const path = "core/target/restheart${{ matrix.os == 'windows-latest' ? '.exe' : '' }}";
            const content = fs.readFileSync(path);

            // Retrieve the release by tag name
            const release = await github.repos.getReleaseByTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag: '8.1.0'
            });

            // Upload the asset to the release
            await github.repos.uploadReleaseAsset({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: release.data.id,
              name: `restheart-${{ matrix.arch }}${{ matrix.os == 'windows-latest' ? '.exe' : '' }}`,
              data: content,
              headers: {
                'content-type': 'application/octet-stream',
                'content-length': content.length
              }
            });
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker-publish:
    runs-on: ubuntu-latest
    needs: build-and-upload
    if: ${{ needs.build-and-upload.outputs.ubuntu == 'true' }}
    steps:
      - uses: actions/checkout@v4

      - name: Download Linux Binary Artifact
        uses: actions/download-artifact@v4
        with:
          name: restheart

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set VERSION
        id: vars
        run: |
          echo "VERSION=$(echo ${GITHUB_REF:10})" >> $GITHUB_ENV

      - name: Build and Push multi-arch native Docker images
        uses: docker/build-push-action@v6
        with:
          context: ./core/
          file: ./core/Dockerfile.native
          push: true # push all images built
          pull: true # pull all required images before building
          tags: |
            softinstigate/restheart-native:latest,
            softinstigate/restheart-native:8,
            softinstigate/restheart-native:8.1,
            softinstigate/restheart-native:8.1.0
