name: Native Image Snapshot

on: workflow_dispatch # Manually trigger the workflow

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4

      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: "21" # See 'Options' section below for all supported versions
          distribution: "graalvm-community" # See 'Options' section below for all available distributions
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache: "maven"
          native-image-job-reports: "true"

      - name: Build native Linux executable
        run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          java --version
          native-image --version
          mvn package -Pnative -DskipTests

      - name: Upload native Linux executable
        uses: actions/upload-artifact@v4
        with:
          name: restheart-linux-amd64
          path: core/target/restheart
          overwrite: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set SHA
        id: vars
        run: |
          echo "SHA=$(echo ${GITHUB_SHA:0:7})" >> $GITHUB_ENV

      - name: Build and Push multi-arch native Docker images
        uses: docker/build-push-action@v6
        with:
          context: ./core/
          file: ./core/Dockerfile.native
          platforms: |
            linux/amd64,
            linux/arm64,
            linux/ppc64le,
            linux/s390x
          push: true # push all images built
          pull: true # pull all required images before building
          tags: |
            softinstigate/restheart-snapshot:${{ env.SHA }}-native
            ${{ github.ref == 'refs/heads/master' && 'softinstigate/restheart-snapshot:latest-native' || '' }}
