# This workflow build and test pull requests

name: Build pull request

on:
  pull_request:
    branches:
      - "*"
    types: [opened, synchronize, reopened]
    paths:
      - "**/*.java" # Trigger on any Java file change
      - "**/*.xml" # Trigger on any xml file change

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mongodb-version: ["5.0", "6.0", "7.0"]
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "maven"

      - name: Build and Test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
        run: |
          mvn -B clean verify -Dmongodb.version="${{ matrix.mongodb-version }}"
