# This workflow builds and tests pull requests

name: Build pull request

on:
  pull_request:
    branches:
      - "*"
    types: [opened, synchronize, reopened]

jobs:
  build_and_test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        mongodb-version: ["5.0", "6.0", "7.0"]
    steps:
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Cache Maven Repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - uses: actions/checkout@v4

      - name: Build and Test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
        run: |
          MAVEN_OPTS="--add-opens=java.base/java.util=ALL-UNNAMED \
                      --add-opens=java.base/java.lang.reflect=ALL-UNNAMED \
                      --add-opens=java.base/java.text=ALL-UNNAMED \
                      --add-opens=java.desktop/java.awt.font=ALL-UNNAMED" \
          mvn -B clean verify -Dmongodb.version="${{ matrix.mongodb-version }}"
