# This workflow builds stable releases

name: Build stable release

on:
  push:
    branches:
      - "!master" # Ignore the master branch
    tags:
      - "*" # Trigger on any tag

jobs:
  # Build and test the project
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        mongodb-version: ["5.0", "6.0"]
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "maven"

      - name: Build and Test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
        run: |
          mvn -B clean verify -Dmongodb.version="${{ matrix.mongodb-version }}"

  # Deploy the project to Maven Central and DockerHub
  deploy:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        mongodb-version: ["7.0"]
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "maven"

      - name: Set VERSION
        id: vars
        run: |
          echo "VERSION=$(echo ${GITHUB_REF:10})" >> $GITHUB_ENV

      - name: Import private gpg key
        run: |
          printf "%s" "$GPG_PRIVATE_KEY" > private.key
          gpg --pinentry-mode=loopback --batch --yes --fast-import private.key
        continue-on-error: true
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Deploy to Maven Central
        run: |
          MAVEN_OPTS="--add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.text=ALL-UNNAMED --add-opens=java.desktop/java.awt.font=ALL-UNNAMED" \
          mvn -B deploy -Pdeploy -Dmongodb.version="${{ matrix.mongodb-version }}" -s settings.xml
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          GPG_KEY_NAME: ${{ secrets.GPG_KEY_NAME }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push multi-arch Docker images
        uses: docker/build-push-action@v6
        with:
          context: ./core/
          platforms: |
            linux/amd64,
            linux/arm64,
            linux/ppc64le,
            linux/s390x
          push: true # push all images built
          pull: true # pull all required images before building
          tags: |
            softinstigate/restheart:latest,
            softinstigate/restheart:8,
            softinstigate/restheart:8.1,
            softinstigate/restheart:${{ env.VERSION }}

      - name: Build and Push GraalVM Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./core/
          file: ./core/Dockerfile.graalvm
          platforms: |
            linux/amd64,
            linux/arm64
          push: true # push all images built
          pull: true # pull all required images before building
          tags: |
            softinstigate/restheart:latest-graalvm,
            softinstigate/restheart:8-graalvm,
            softinstigate/restheart:8.1-graalvm,
            softinstigate/restheart:${{ env.VERSION }}-graalvm

      - name: Build and Push distroless docker image
        uses: docker/build-push-action@v6
        with:
          context: ./core/
          file: ./core/Dockerfile.distroless
          platforms: |
            linux/amd64,
            linux/arm64,
            linux/ppc64le
          push: true # push all images built
          pull: true # pull all required images before building
          tags: |
            softinstigate/restheart:latest-distroless,
            softinstigate/restheart:8-distroless,
            softinstigate/restheart:8.1-distroless,
            softinstigate/restheart:${{ env.VERSION }}-distroless

      - name: Upload GitHub release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body: |
            # Release ${{ env.VERSION }}
          files: |
            core/target/restheart.tar.gz
            core/target/restheart.zip
          draft: true
          prerelease: false
