# This workflow builds stable releases

name: Build stable release

on:
  push:
    branches:
      - "!master" # Ignore the master branch
    tags:
      - "*"

jobs:
  setup:
    runs-on: ubuntu-22.04
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    strategy:
      matrix:
        include:
          - mongodb-version: "5.0"
          - mongodb-version: "6.0"
          - mongodb-version: "7.0"
            deploy: true
    steps:
      - name: Set the VERSION
        id: vars
        run: |
          echo "VERSION=$(echo ${GITHUB_REF:10})" >> $GITHUB_ENV
          echo "DEPLOY=${{ matrix.deploy }}" >> $GITHUB_ENV

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Cache Maven Repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Import private GPG key
        if: ${{ matrix.deploy }}
        run: |
          printf "%s" "$GPG_PRIVATE_KEY" > private.key
          gpg --pinentry-mode=loopback --batch --yes --fast-import private.key
          rm private.key
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Set up QEMU
        if: ${{ matrix.deploy }}
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        if: ${{ matrix.deploy }}
        uses: docker/setup-buildx-action@v3

  build_and_test:
    runs-on: ubuntu-22.04
    needs: setup
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    strategy:
      matrix:
        mongodb-version: ["5.0", "6.0", "7.0"]
    steps:
      - uses: actions/checkout@v4

      - name: Build and Test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
        run: mvn -B clean verify -Dmongodb.version="${{ matrix.mongodb-version }}"

  deploy:
    runs-on: ubuntu-22.04
    needs: build_and_test
    if: "!contains(github.event.head_commit.message, 'skip ci') && env.DEPLOY == 'true'"
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Maven Central
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          GPG_KEY_NAME: ${{ secrets.GPG_KEY_NAME }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          MAVEN_OPTS="--add-opens=java.base/java.util=ALL-UNNAMED \
                      --add-opens=java.base/java.lang.reflect=ALL-UNNAMED \
                      --add-opens=java.base/java.text=ALL-UNNAMED \
                      --add-opens=java.desktop/java.awt.font=ALL-UNNAMED" \
          mvn -B deploy -Pdeploy -s settings.xml

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push multi-arch Docker images
        uses: docker/build-push-action@v6
        with:
          context: ./core/
          platforms: linux/amd64,linux/arm64/v8,linux/ppc64le,linux/s390x
          push: true # push all images built
          pull: true # pull all required images before building
          tags: |
            softinstigate/restheart:latest,
            softinstigate/restheart:8,
            softinstigate/restheart:8.0,
            softinstigate/restheart:${{ env.VERSION }}

      - name: Build and Push GraalVM Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./core/
          file: ./core/Dockerfile.graalvm
          push: true # push all images built
          pull: true # pull all required images before building
          tags: |
            softinstigate/restheart:graalvm,
            softinstigate/restheart:latest-graalvm,
            softinstigate/restheart:8-graalvm,
            softinstigate/restheart:${{ env.VERSION }}-graalvm

      - name: Build and Push distroless Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./core/
          file: ./core/Dockerfile.distroless
          push: true # push all images built
          pull: true # pull all required images before building
          tags: |
            softinstigate/restheart:distroless,
            softinstigate/restheart:latest-distroless,
            softinstigate/restheart:8-distroless,
            softinstigate/restheart:${{ env.VERSION }}-distroless

  release:
    runs-on: ubuntu-22.04
    needs: deploy
    if: "!contains(github.event.head_commit.message, 'skip ci') && env.DEPLOY == 'true'"
    steps:
      - name: Upload GitHub release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body: |
            Release ${{ github.ref_name }}
          files: |
            core/target/restheart.tar.gz
            core/target/restheart.zip
          draft: true
          prerelease: false
